package delivery

import (
	"context"
	"crypto/sha256"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/follenfang/lycheedev/internal/bridge"
)

const slotMarker = ".lycheedev-slots.json"
const slotPoolSchema = "lycheedev.slots.v3"
const previousSlotPoolSchema = "lycheedev.slots.v2"
const legacySlotPoolSchema = "lycheedev.slots.v1"
const slotPoolMigrationSchema = "lycheedev.slots.migration.v3"
const slotPoolManifestLimit = 256 << 10

type SlotFile struct {
	PayloadHash    string `json:"payloadHash"`
	PendingHash    string `json:"pendingHash,omitempty"`
	Nonce          string `json:"nonce,omitempty"`
	Runtime        string `json:"runtime,omitempty"`
	Consumer       string `json:"consumer,omitempty"`
	Consumed       bool   `json:"consumed"`
	RetiredRuntime string `json:"retiredRuntime,omitempty"`
	RetiredProcess bool   `json:"retiredProcess,omitempty"`
}
type SlotPool struct {
	SourceSchema   string     `json:"sourceSchema,omitempty"`
	PendingVersion string     `json:"pendingVersion,omitempty"`
	Schema         string     `json:"schema"`
	Version        string     `json:"version"`
	State          string     `json:"state"`
	Files          []SlotFile `json:"files"`
}

func SlotDirectory(parent string, index int) string {
	return filepath.Join(parent, fmt.Sprintf("Lychee Dev Slot %02d", index))
}
func slotDigest(b []byte) string { return fmt.Sprintf("%x", sha256.Sum256(b)) }
func slotStaticForSchema(index int, version, schema string) map[string][]byte {
	transport := "memory-slot-v3"
	if schema == legacySlotPoolSchema {
		transport = "memory-slot-v1"
	} else if schema == previousSlotPoolSchema {
		transport = "memory-slot-v2"
	}
	name := fmt.Sprintf("Lychee Dev Slot %02d", index)
	return map[string][]byte{
		name + ".toc": []byte(fmt.Sprintf("## Interface: 120100, 50504, 38002, 16001\n## Title: Lychee Dev input slot %02d\n## Version: %s\n## LoadOnDemand: 1\n## X-Lychee-Slot: %d\n## X-Lychee-Transport: %s\nPayload.lua\nLoader.lua\n", index, version, index, transport)),
		"Loader.lua":  []byte(fmt.Sprintf("local envelope = LycheeDevSlotEnvelope\nLycheeDevSlotEnvelope = nil\nlocal ns = LycheeDevInternal\nif ns and ns.SlotRuntime then ns.SlotRuntime.Receive(%d, envelope) end\n", index)),
	}
}

func readSlotPool(parent string) (SlotPool, error) {
	return readExactLegacySlotPool(parent)
}

// Old schemas are installation metadata only. No business operation admits them.
func validSlotPoolShape(pool SlotPool) bool {
	if pool.Version == "" {
		return false
	}
	switch pool.Schema {
	case slotPoolSchema:
		return len(pool.Files) == bridge.SlotCount && pool.SourceSchema == ""
	case legacySlotPoolSchema:
		return len(pool.Files) == 64 && pool.State == "ready" && pool.SourceSchema == ""
	case previousSlotPoolSchema:
		return len(pool.Files) == bridge.SlotCount && pool.State == "ready" && pool.SourceSchema == ""
	case slotPoolMigrationSchema:
		return pool.State == "upgrading" && pool.PendingVersion != "" && (pool.SourceSchema == legacySlotPoolSchema && len(pool.Files) == 64 || (pool.SourceSchema == previousSlotPoolSchema || pool.SourceSchema == slotPoolSchema) && len(pool.Files) == bridge.SlotCount)
	}
	return false
}

func readSlotFile(path string, limit int64) ([]byte, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Size() > limit {
		return nil, ErrInstallation
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	b, err := io.ReadAll(io.LimitReader(f, limit+1))
	if int64(len(b)) > limit {
		return nil, ErrInstallation
	}
	return b, err
}
func plainSlotDirectory(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 || resolved != path {
		return fmt.Errorf("%w: redirected slot", ErrInstallation)
	}
	return nil
}

func exactSlotFileCount(path string) error {
	entries, err := os.ReadDir(path)
	if err != nil {
		return err
	}
	if len(entries) != 3 {
		return fmt.Errorf("%w: unexpected slot files", ErrInstallation)
	}
	return nil
}

// Installation maintenance checks old generated bytes without decoding or
// resuming any old business envelope. Upgrade refuses unresolved reservations.
func inspectSlotPool(ctx context.Context, parent string, pool SlotPool, version string) (SlotPool, error) {
	if pool.State != "ready" || pool.Version != version {
		return pool, ErrInstallation
	}
	var err error
	for i, item := range pool.Files {
		if err = ctx.Err(); err != nil {
			return pool, err
		}
		dir := SlotDirectory(parent, i+1)
		if err = plainSlotDirectory(dir); err != nil {
			return pool, err
		}
		if err = exactSlotFileCount(dir); err != nil {
			return pool, err
		}
		for name, want := range slotStaticForSchema(i+1, version, pool.Schema) {
			actual, e := readSlotFile(filepath.Join(dir, name), 16384)
			if e != nil {
				return pool, e
			}
			if slotDigest(actual) != slotDigest(want) {
				return pool, ErrInstallation
			}
		}
		actual, e := readSlotFile(filepath.Join(dir, "Payload.lua"), 2<<20)
		if e != nil {
			return pool, e
		}
		hash := slotDigest(actual)
		if hash != item.PayloadHash && hash != item.PendingHash {
			return pool, fmt.Errorf("%w: slot payload drift", ErrInstallation)
		}
	}
	return pool, nil
}
