// Package luals adapts the pinned, offline LuaLS runtime through its public
// check command and Language Server Protocol. It does not import delivery or
// codebase; callers supply release verification and workspace identity checks.
package luals

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"
)

var (
	ErrUnavailable = errors.New("luals.unavailable")
	ErrFailed      = errors.New("luals.failed")
	ErrBudget      = errors.New("luals.input_budget")
	ErrUnsupported = errors.New("luals.unsupported")
)

const MaxFileBytes = 1 << 20
const MaxDefinitionsBytes = 8 << 20
const DefinitionPath = "@environment/api.d.lua"
const MaxFiles = 2048
const MaxTotalBytes = 32 << 20
const MaxReportBytes = 8 << 20
const MaxWorkspaceFiles = 20000
const MaxWorkspaceBytes int64 = 1 << 30

type Identity struct {
	Name     string `json:"name"`
	Version  string `json:"version"`
	Platform string `json:"platform"`
	URL      string `json:"url"`
	Bytes    int64  `json:"bytes"`
	SHA256   string `json:"sha256"`
}

// pinnedRuntimeJSON is generated by `node tools/luals.mjs generate` from
// release/tools/luals.json. That file is the sole version/digest authority.
func Pinned() Identity {
	var value Identity
	_ = json.Unmarshal([]byte(pinnedRuntimeJSON), &value)
	return value
}

type Runtime struct {
	directory       string
	contextIdentity string
	Identity        Identity
}

// Open verifies the complete release inventory before trusting a private
// executable. The callback is supplied by the CLI composition layer.
func Open(ctx context.Context, releaseRoot string, verifyRelease func(context.Context, string) error) (*Runtime, error) {
	if runtime.GOOS != "windows" || runtime.GOARCH != "amd64" {
		return nil, fmt.Errorf("%w: Windows amd64 is required", ErrUnavailable)
	}
	if releaseRoot == "" {
		executable, err := os.Executable()
		if err != nil {
			return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
		}
		for dir, depth := filepath.Dir(executable), 0; depth < 4; dir, depth = filepath.Dir(dir), depth+1 {
			if _, err := os.Stat(filepath.Join(dir, "release.json")); err == nil {
				releaseRoot = dir
				break
			}
		}
	}
	if releaseRoot == "" || verifyRelease == nil {
		return nil, fmt.Errorf("%w: complete verified release required", ErrUnavailable)
	}
	if err := verifyRelease(ctx, releaseRoot); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	dir, err := filepath.Abs(filepath.Join(releaseRoot, "payload", "tool", "luals"))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrUnavailable, err)
	}
	metadata, err := os.ReadFile(filepath.Join(dir, "runtime.json"))
	if err != nil || !bytes.Equal(bytes.TrimSpace(metadata), []byte(pinnedRuntimeJSON)) {
		return nil, fmt.Errorf("%w: pinned runtime identity mismatch", ErrUnavailable)
	}
	for _, name := range []string{"bin/lua-language-server.exe", "bin/main.lua", "main.lua", "LICENSE"} {
		if info, err := os.Stat(filepath.Join(dir, name)); err != nil || !info.Mode().IsRegular() {
			return nil, fmt.Errorf("%w: missing runtime file %s", ErrUnavailable, name)
		}
	}
	manifest, err := os.Open(filepath.Join(releaseRoot, "release.json"))
	if err != nil {
		return nil, fmt.Errorf("%w: release manifest", ErrUnavailable)
	}
	raw, readErr := io.ReadAll(io.LimitReader(manifest, (1<<20)+1))
	manifest.Close()
	if readErr != nil || len(raw) > 1<<20 {
		return nil, ErrBudget
	}
	config, _ := ConfigurationIdentity()
	digest := sha256.Sum256(append(raw, config...))
	return &Runtime{directory: dir, Identity: Pinned(), contextIdentity: hex.EncodeToString(digest[:])}, nil
}

type Position struct {
	Line      int `json:"line"`
	Character int `json:"character"`
}
type Range struct {
	Start Position `json:"start"`
	End   Position `json:"end"`
}
type Diagnostic struct {
	Path     string `json:"path"`
	Code     string `json:"code"`
	Message  string `json:"message"`
	Range    Range  `json:"range"`
	Severity int    `json:"severity"`
}
type Result struct {
	Runtime          Identity     `json:"runtime"`
	State            string       `json:"state"`
	Files            int          `json:"files"`
	Passed           bool         `json:"passed"`
	Diagnostics      []Diagnostic `json:"diagnostics"`
	PositionEncoding string       `json:"positionEncoding"`
	Raw              []byte       `json:"-"`
	Config           []byte       `json:"-"`
}

func validateFiles(files map[string][]byte, definitions []byte) error {
	if len(files) > MaxFiles || len(definitions) > MaxDefinitionsBytes {
		return ErrBudget
	}
	total := len(definitions)
	for name, data := range files {
		if !filepath.IsLocal(name) || filepath.Ext(name) != ".lua" || len(data) > MaxFileBytes {
			return fmt.Errorf("%w: %s", ErrBudget, name)
		}
		total += len(data)
		if total > MaxTotalBytes {
			return ErrBudget
		}
	}
	return nil
}

func frozenWorkspace(files map[string][]byte, definitions []byte) (dir, workspace, library string, allowed map[string]string, cleanup func(), err error) {
	if err = validateFiles(files, definitions); err != nil {
		return
	}
	dir, err = os.MkdirTemp("", "lycheedev-luals-")
	if err != nil {
		return
	}
	cleanup = func() { _ = os.RemoveAll(dir) }
	workspace, library = filepath.Join(dir, "workspace"), filepath.Join(dir, "definitions")
	for _, path := range []string{workspace, library, filepath.Join(dir, "log"), filepath.Join(dir, "meta")} {
		if err = os.MkdirAll(path, 0700); err != nil {
			cleanup()
			return
		}
	}
	allowed = make(map[string]string, len(files))
	for name, data := range files {
		path := filepath.Join(workspace, name)
		if err = os.MkdirAll(filepath.Dir(path), 0700); err != nil {
			cleanup()
			return
		}
		if err = os.WriteFile(path, data, 0600); err != nil {
			cleanup()
			return
		}
		allowed[strings.ToLower(filepath.Clean(path))] = name
	}
	if err = os.WriteFile(filepath.Join(library, "api.d.lua"), definitions, 0600); err != nil {
		cleanup()
		return
	}
	return
}

func configuration(library string) ([]byte, error) {
	return json.Marshal(map[string]any{
		"runtime.version": "Lua 5.1", "runtime.path": []string{"?.lua", "?/init.lua"}, "runtime.plugin": "", "runtime.pluginArgs": []string{},
		"workspace.library": []string{library}, "workspace.checkThirdParty": "Disable", "workspace.userThirdParty": []string{}, "workspace.dofileRoots": []string{},
		"workspace.ignoreDir": []string{".git", "node_modules"}, "workspace.useGitIgnore": false, "workspace.ignoreSubmodules": false,
		"files.associations": map[string]string{}, "files.exclude": map[string]bool{"**/.git": true, "**/node_modules": true},
		"workspace.maxPreload": MaxWorkspaceFiles, "workspace.preloadFileSize": MaxFileBytes / 1024,
		"addonManager.enable": false, "telemetry.enable": false,
		"diagnostics.libraryFiles": "Disable", "diagnostics.neededFileStatus": map[string]string{"codestyle-check": "None"},
	})
}

// Check uses LuaLS's documented --check operation. Process exit plus a valid
// report is the completion signal, including when every file has no diagnostics.
func (r *Runtime) Check(ctx context.Context, files map[string][]byte, definitions []byte) (Result, error) {
	result := Result{Runtime: r.Identity, State: "unavailable", Diagnostics: []Diagnostic{}, PositionEncoding: "utf-16; zero-based lines and characters"}
	if err := ctx.Err(); err != nil {
		return result, err
	}
	dir, workspace, library, allowed, cleanup, err := frozenWorkspace(files, definitions)
	if err != nil {
		return result, err
	}
	defer cleanup()
	result.Config, err = configuration(library)
	if err != nil {
		return result, err
	}
	config := filepath.Join(dir, "config.json")
	if err = os.WriteFile(config, result.Config, 0600); err != nil {
		return result, err
	}
	out := filepath.Join(dir, "report.json")
	bounded, cancel := context.WithTimeout(ctx, 90*time.Second)
	defer cancel()
	command := exec.CommandContext(bounded, filepath.Join(r.directory, "bin", "lua-language-server.exe"),
		"--check="+workspace, "--num_threads=1", "--configpath="+config,
		"--logpath="+filepath.Join(dir, "log"), "--metapath="+filepath.Join(dir, "meta"),
		"--check_out_path="+out, "--check_format=json", "--checklevel=Warning", "--quiet")
	command.Dir = dir
	command.WaitDelay = 2 * time.Second
	hideProcess(command)
	var output cappedWriter
	command.Stdout, command.Stderr = &output, &output
	runErr := runGuarded(bounded, command)
	if runErr != nil {
		if ctx.Err() != nil {
			return result, ctx.Err()
		}
		if bounded.Err() != nil {
			return result, fmt.Errorf("%w: 90 second deadline", ErrFailed)
		}
		var exit *exec.ExitError
		if !errors.As(runErr, &exit) || exit.ExitCode() != 1 {
			return result, fmt.Errorf("%w: %v (%s)", ErrFailed, runErr, output.String())
		}
	}
	file, err := os.Open(out)
	if err != nil {
		return result, fmt.Errorf("%w: no completed JSON report (%s)", ErrFailed, output.String())
	}
	defer file.Close()
	result.Raw, err = io.ReadAll(io.LimitReader(file, MaxReportBytes+1))
	if err != nil || len(result.Raw) > MaxReportBytes {
		return result, fmt.Errorf("%w: report budget", ErrFailed)
	}
	result.Diagnostics, err = decodeReport(result.Raw, allowed)
	if err != nil {
		return result, err
	}
	if runErr != nil && len(result.Diagnostics) == 0 {
		return result, fmt.Errorf("%w: nonzero exit without diagnostics", ErrFailed)
	}
	result.State, result.Files, result.Passed = "checked", len(files), len(result.Diagnostics) == 0
	return result, nil
}

func decodeReport(raw []byte, allowed map[string]string) ([]Diagnostic, error) {
	// The public --check JSON format emits [] when no diagnostics exist.
	if bytes.Equal(bytes.TrimSpace(raw), []byte("[]")) {
		return []Diagnostic{}, nil
	}
	var report map[string][]Diagnostic
	if err := json.Unmarshal(raw, &report); err != nil || report == nil {
		return nil, fmt.Errorf("%w: invalid JSON report", ErrFailed)
	}
	result := []Diagnostic{}
	for uri, diagnostics := range report {
		u, err := url.Parse(uri)
		if err != nil || u.Scheme != "file" || u.Host != "" {
			return nil, fmt.Errorf("%w: report URI", ErrFailed)
		}
		path := u.Path
		if len(path) > 2 && path[0] == '/' && path[2] == ':' {
			path = path[1:]
		}
		name, ok := allowed[strings.ToLower(filepath.Clean(filepath.FromSlash(path)))]
		if !ok {
			return nil, fmt.Errorf("%w: report outside frozen closure", ErrFailed)
		}
		for _, diagnostic := range diagnostics {
			if diagnostic.Code == "" || diagnostic.Severity < 1 || diagnostic.Severity > 2 || diagnostic.Range.Start.Line < 0 || diagnostic.Range.Start.Character < 0 || diagnostic.Range.End.Line < diagnostic.Range.Start.Line || diagnostic.Range.End.Character < 0 || (diagnostic.Range.End.Line == diagnostic.Range.Start.Line && diagnostic.Range.End.Character < diagnostic.Range.Start.Character) {
				return nil, fmt.Errorf("%w: invalid diagnostic", ErrFailed)
			}
			diagnostic.Path = name
			result = append(result, diagnostic)
			if len(result) > 10000 {
				return nil, fmt.Errorf("%w: diagnostic budget", ErrFailed)
			}
		}
	}
	sort.Slice(result, func(i, j int) bool {
		a, b := result[i], result[j]
		if a.Path != b.Path {
			return a.Path < b.Path
		}
		if a.Range.Start.Line != b.Range.Start.Line {
			return a.Range.Start.Line < b.Range.Start.Line
		}
		if a.Range.Start.Character != b.Range.Start.Character {
			return a.Range.Start.Character < b.Range.Start.Character
		}
		return a.Code < b.Code
	})
	return result, nil
}

type cappedWriter struct {
	mu     sync.Mutex
	buffer bytes.Buffer
}

func (w *cappedWriter) Write(p []byte) (int, error) {
	w.mu.Lock()
	defer w.mu.Unlock()
	n := len(p)
	if remaining := 8192 - w.buffer.Len(); remaining > 0 {
		if len(p) > remaining {
			p = p[:remaining]
		}
		_, _ = w.buffer.Write(p)
	}
	return n, nil
}
func (w *cappedWriter) String() string { w.mu.Lock(); defer w.mu.Unlock(); return w.buffer.String() }

// ConfigurationIdentity describes the effective configuration independently of
// the owned temporary library path, whose definitions digest belongs in the
// composition identity. It cannot be overridden by a source .luarc.
func ConfigurationIdentity() ([]byte, error) { return configuration("@verified-generated-definitions") }

// ReleaseRoot exposes the verified release location to composition; it is not
// accepted as an executable path by the broker protocol.
func (r *Runtime) ReleaseRoot() string { return filepath.Dir(filepath.Dir(filepath.Dir(r.directory))) }

func (r *Runtime) ContextIdentity() string { return r.contextIdentity }
