// Release-time preparation only. npm receives the complete pinned runtime;
// installation and CLI startup never download executable code.
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readZip } from './zip.mjs';

const repository = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const runtimeBytes = Buffer.from(JSON.stringify(JSON.parse(readFileSync(join(repository, 'release/tools/luals.json'), 'utf8'))));
export const luaRuntime = JSON.parse(runtimeBytes);
const hash = bytes => createHash('sha256').update(bytes).digest('hex');

// One canonical manifest; the Go literal is generated and checked in CI.
export function generateGoIdentity({ check = false } = {}) {
  const target = join(repository, 'internal/luals/identity_generated.go');
  const source = `// Code generated by node tools/luals.mjs generate; DO NOT EDIT.\npackage luals\n\nconst pinnedRuntimeJSON = ${JSON.stringify(runtimeBytes.toString('utf8'))}\n`;
  if (check) {
    if (readFileSync(target, 'utf8') !== source) throw new Error('luals.generated_identity_drift');
  } else writeFileSync(target, source);
}

export function runtimeFiles(archive) {
  if (archive.length !== luaRuntime.bytes || hash(archive) !== luaRuntime.sha256) throw new Error('luals.archive_integrity');
  const files = readZip(archive);
  if (files.size > 5000) throw new Error('luals.file_limit');
  let total = 0;
  const seen = new Set();
  for (const [name, bytes] of files) {
    if (name.endsWith('/') && bytes.length === 0) { files.delete(name); continue; }
    if (name.length > 190 || name.split('/').some(p => !p || p === '.' || p === '..' || /[\\:<>"|?*\x00-\x1f]|[ .]$/.test(p)) || seen.has(name.toLowerCase())) throw new Error('luals.invalid_archive_path');
    seen.add(name.toLowerCase());
    total += bytes.length;
    if (total > 64 * 1024 * 1024) throw new Error('luals.extracted_limit');
  }
  for (const required of ['bin/lua-language-server.exe', 'bin/main.lua', 'main.lua', 'LICENSE']) {
    if (!files.has(required)) throw new Error(`luals.missing_runtime: ${required}`);
  }
  files.set('runtime.json', runtimeBytes);
  return files;
}

function buildGitPointer(name, bytes) {
  const match = /^meta\/3rd\/([^/]+)\/\.git$/.exec(name);
  return match !== null && bytes.equals(Buffer.from(`gitdir: ../../../.git/modules/meta/3rd/${match[1]}\n`));
}

export async function stageLuaLS(stage, resources, { archivePath, fetchImpl = fetch } = {}) {
  let archive;
  if (archivePath) archive = readFileSync(archivePath);
  else {
    const response = await fetchImpl(luaRuntime.url, { signal: AbortSignal.timeout(120000) });
    if (!response.ok) throw new Error(`luals.download_failed: ${response.status}`);
    const chunks = []; let length = 0;
    for await (const chunk of response.body) {
      length += chunk.length;
      if (length > luaRuntime.bytes) throw new Error('luals.archive_size');
      chunks.push(chunk);
    }
    archive = Buffer.concat(chunks);
  }
  for (const [name, bytes] of runtimeFiles(archive)) {
    // The official archive includes Git submodule control pointers. npm pack
    // always omits .git entries; they are not LuaLS runtime inputs and must
    // not enter the sealed payload inventory. Validate their exact form.
    if (name.endsWith('/.git')) {
      if (!buildGitPointer(name, bytes)) throw new Error(`luals.unexpected_git_pointer: ${name}`);
      continue;
    }
    const path = `tool/luals/${name}`;
    const destination = join(stage, 'payload', path);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, bytes);
    resources.push({ path, bytes: bytes.length, sha256: hash(bytes) });
  }
  resources.sort((a, b) => a.path < b.path ? -1 : a.path > b.path ? 1 : 0);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv[2] === 'generate') generateGoIdentity();
  else if (process.argv[2] === 'check') generateGoIdentity({ check: true });
  else throw new Error('usage: node tools/luals.mjs generate|check');
}
